services:
    # we dont need this for now. I'm fixing the node engines to the right version
    #  backend:
    #    build:
    #     context: .
    #     dockerfile: ./Dockerfile
    #    ports:
    #      - 4000:4000
    #    depends_on:
    #      - db
    #    environment:
    #      DATABASE_URL: postgres://admin:admin@db:5432/fs_admin
    #    networks:
    #      - fs_admin
     db:
       image: postgres:15-alpine
       environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin
         POSTGRES_DB: fs_admin
       volumes:
         - pgdata:/var/lib/postgresql/data
       networks:
         - fs_admin
networks:
  fs_admin:
    driver: bridge
volumes:
  pgdata:
    driver: local